version: '3.8'

services:
  aria-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: aria-backend-light
    environment:
      - ENVIRONMENT=production
      - REDIS_MAX_MEMORY=512mb
      - POSTGRES_MAX_CONNECTIONS=20
      - WORKER_PROCESSES=4
      - MEMORY_LIMIT=2g
      - CPU_LIMIT=2
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./configs:/app/configs
      - ./logs:/app/logs:rw
      - aria_data:/app/data
    restart: unless-stopped
    mem_limit: 2g
    cpus: 2.0
    depends_on:
      - redis-light
      - postgres-light

  redis-light:
    image: redis:7-alpine
    container_name: aria-redis-light
    command: >
      redis-server 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --rdbcompression yes
      --rdbchecksum yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5

  postgres-light:
    image: postgres:13-alpine
    container_name: aria-postgres-light
    environment:
      - POSTGRES_DB=aria_trading
      - POSTGRES_USER=aria_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_MAX_CONNECTIONS=20
      - POSTGRES_SHARED_BUFFERS=128MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0

  aria-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aria-frontend-light
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS=--max_old_space_size=512
    ports:
      - "3000:3000"
    depends_on:
      - aria-backend
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0

  nginx:
    image: nginx:alpine
    container_name: aria-nginx-light
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.light.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - aria-frontend
      - aria-backend
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.25

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  aria_data:
    driver: local

networks:
  default:
    driver: bridge
